server:
  port: 8080

spring:
  application:
    name: auth-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/garbigo_auth
    redis:
      host: localhost
      port: 6379

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  mail:
    host: smtp.gmail.com
    port: 587
    username: thepeacemakerske@gmail.com
    password: 'mjyk cibp uids weiy'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # ====================== MULTIPART CONFIGURATION ======================
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 2KB

cloudinary:
  cloud-name: thepeacemakersllc
  api-key: 279386562332176
  api-secret: _UVXMFDd78NXrqPrIQA-JJK_u98

jwt:
  secret: pR5q9T8wX2z7C4v3B6nM1kLj8HgFdEaSbQcW3eZr4tY7uKiOp9L0mN2bV5cX8jH
  expiration: 2592000

rate-limit:
  requests-per-minute: 20

rabbitmq:
  queue:
    user-created: user-created-queue

app:
  url: http://localhost:3000

google:
  client-id: your-google-client-id.apps.googleusercontent.com

facebook:
  app-id: your-facebook-app-id
  app-secret: your-facebook-app-secret

apple:
  client-id: your-apple-service-id